container:
  image: golang:latest

env:
  GOROOT_BOOTSTRAP: /usr/local/go
  CGO_ENABLED: "0"

allbash_task:
  setup_script:
  - echo $CIRRUS_WORKING_DIR
  - go version
  - go env
  - lsb_release -a || true
  - cat etc/debian_release || true
  - echo "Cloning"
  - mkdir golang
  - cd golang
  - git version
  - git clone --depth=1 --branch master --single-branch --no-tags https://go.googlesource.com/go
  - pwd
  - cd go
  - echo "On tip"
  - git log -1 --pretty=short

  build_script:
  - pwd
  - cd golang/go/src
  - sh ./all.bash

  always:
    binaries_artifacts:
      path: "golang/go/bin/go*"
