name: go-on-tip
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.14
      id: go

    - name: Clone master of go
      run: |
        git clone https://github.com/golang/go.git --branch master --single-branch --no-tags
        cd go/src
        git log -1 --pretty=short

    - name: Build
      run: |
        cd go/src
        export GOROOT_BOOTSTRAP=$(go env GOROOT)
        sh ./make.bash

    - name: Test
      run: |
        cd go/bin
        export GOROOT=
        go tool dist version
        go tool dist test

    - name: Upload go executable
      uses: actions/upload-artifact@v1
      with:
        name: gotip
        path: go/bin/go